--- #YAML:1.0
name:                Lingua-PT-Abbrev
version:             0.06
abstract:            An abbreviations dictionary manager for NLP
license:             ~
author:              
    - Alberto Simões <ambs@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.43_01
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
